#!/usr/bin/env python3
"""Generate the Releases table fragment for ``SONIC/releases/index.md``.

One row per git ``rls-*`` tag that also has an entry in ``releases.yaml``.
See ``releases_lib.py`` for discovery rules and the version switcher.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from releases_lib import (
    load_releases,
    published_tags,
    release_branch,
    tag_to_version,
)

_RELEASES_DIR = Path(__file__).resolve().parents[1] / "SONIC" / "releases"
_OUT = _RELEASES_DIR / "_releases_table.md"

_COLUMNS = [
    "Release",
    "Release Tag",
    "Release Branch",
    "Marvell SAI Version",
    "OCP SAI Version",
    "Lifecycle",
    "URL",
]


def _repo_url() -> str:
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get(
        "GITHUB_REPOSITORY", "MarvellEmbeddedProcessors/marvell-sonic-buildimage"
    )
    return f"{server}/{repo}"


def _current_version() -> str:
    ref = os.environ.get("GITHUB_REF_NAME", "")
    return tag_to_version(ref) if ref.startswith("rls-") else "master"


def _notes_href(version: str, current_version: str) -> str:
    if version == current_version:
        return "release-notes.html"
    return f"../../../{version}/SONIC/releases/release-notes.html"


def _ext_link(href: str, text: str, *, title: str | None = None) -> str:
    title_attr = f' title="{title}"' if title else ""
    return (
        f'<a class="reference external" href="{href}"{title_attr} '
        f'target="_blank" rel="noopener">{text}</a>'
    )


def _github_cell(repo_url: str, branch: str) -> str:
    href = f"{repo_url}/tree/{branch}"
    return (
        f'<a class="reference external" href="{href}" '
        f'title="View on GitHub" target="_blank" rel="noopener">'
        f'<i class="fa-brands fa-github fa-lg" aria-hidden="true"></i>'
        f'<span class="visually-hidden">View {branch} on GitHub</span></a>'
    )


def _row(tag: str, info: dict, current_version: str, repo_url: str) -> str:
    version = tag_to_version(tag)
    branch = release_branch(tag, info)

    tag_cell = (
        f'<a class="reference internal" href="{_notes_href(version, current_version)}">'
        f"{tag}</a>"
    )
    marvell_sai = info.get("marvell_sai", "TBD")
    ocp_label = info.get("ocp_sai")
    ocp_url = info.get("ocp_sai_url")
    if ocp_label and ocp_url:
        ocp_cell = _ext_link(ocp_url, ocp_label)
    else:
        ocp_cell = ocp_label or "TBD"
    lifecycle = info.get("lifecycle", "TBD")
    release_label = info.get("release", "TBD")

    cells = [
        release_label,
        tag_cell,
        branch,
        marvell_sai,
        ocp_cell,
        lifecycle,
        _github_cell(repo_url, branch),
    ]
    return "| " + " | ".join(cells) + " |"


def render(out_path: Path | str = _OUT) -> Path:
    out_path = Path(out_path)
    meta = load_releases()
    tags = published_tags(meta)
    current_version = _current_version()
    repo_url = _repo_url()

    header = "| " + " | ".join(_COLUMNS) + " |"
    separator = "|" + "|".join(["---"] * len(_COLUMNS)) + "|"
    if tags:
        rows = [_row(t, meta[t], current_version, repo_url) for t in tags]
    else:
        rows = [
            "| " + " | ".join(["_None yet._"] + [""] * (len(_COLUMNS) - 1)) + " |"
        ]

    lines = [
        "<!-- Generated by _scripts/gen_releases_table.py -- do not edit. -->",
        ":::{table}",
        ":class: table releases-table",
        "",
        header,
        separator,
        *rows,
        ":::",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


if __name__ == "__main__":
    dest = sys.argv[1] if len(sys.argv) > 1 else _OUT
    print(render(dest))
